# Generated by Django 3.0.3 on 2020-08-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200830_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message_html',
            field=models.TextField(editable=False),
        ),
    ]
