# Generated by Django 3.0.3 on 2021-04-06 14:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='message_html',
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
